apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: nlp
spec:
  selector:
    app: apisix
  ports:
    - name: http
      port: 9080
      targetPort: 9080
    - name: admin
      port: 9180
      targetPort: 9180
    - name: https
      port: 9443
      targetPort: 9443
  type: NodePort  # Use LoadBalancer if on cloud
