apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apisix-etcd
  namespace: nlp
spec:
  serviceName: "apisix-etcd"
  replicas: 1
  selector:
    matchLabels:
      app: apisix-etcd
  template:
    metadata:
      labels:
        app: apisix-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.0
          env:
            - name: ETCD_ENABLE_V2
              value: "true"
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1"
          ports:
            - containerPort: 2379
          # Add health probes
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - ETCDCTL_API=3 etcdctl endpoint health
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - ETCDCTL_API=3 etcdctl endpoint health
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: etcd-data
              mountPath: /bitnami/etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
