services:
  # ETCD for APISIX (Latest version)
  etcd:
    image: bitnami/etcd:3.5.12
    container_name: apisix-etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_AUTO_COMPACTION_RETENTION: "1"
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - auth-network

  # APISIX API Gateway (Latest version)
  apisix:
    image: apache/apisix:3.13.0-debian
    container_name: apisix
    restart: always
    depends_on:
      - etcd
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"
      - "9180:9180"
      - "9443:9443"
    networks:
      - auth-network
    environment:
      - APISIX_STAND_ALONE=false

volumes:
  etcd_data:

networks:
  auth-network:
    driver: bridge 